services:
  db:
    container_name: ${PROJECT_NAME}-db
    image: postgres:${POSTGRES_VERSION}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ${POSTGRES_DATA-./config/db}:/var/lib/postgresql/data
  web:
    container_name: ${PROJECT_NAME}-web
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfiles/web.Dockerfile
      args:
        - WEB_DIR=${WEB_DIR}
    ports:
      - 5173:5173
    volumes:
      - ${WEB_DIR}:/app
  server:
    container_name: ${PROJECT_NAME}-server
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfiles/server.Dockerfile
      args:
        - SERVER_DIR=${SERVER_DIR}
    ports:
      - 8000:8000
    environment:
      - PYTHONUNBUFFERED=1
  nginx:
    container_name: ${PROJECT_NAME}-nginx
    restart: always
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
