services:
  db:
    container_name: ${PROJECT_NAME}-db
    image: postgres:${POSTGRES_VERSION}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    ports:
      - "127.0.0.1:${POSTGRES_PORT}:5432"
    volumes:
      - ${POSTGRES_DATA-./config/db}:/var/lib/postgresql/data
  web:
    container_name: ${PROJECT_NAME}-web
    restart: always
    build:
      context: ./
      dockerfile: ./Dockerfiles/web.Dockerfile
      args:
        - WEB_DIR=${WEB_DIR}
    ports:
      - 80:80
    volumes:
      - ${WEB_DIR}:/app
  server:
    container_name: ${PROJECT_NAME}-server
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfiles/server.Dockerfile
      args:
        - SERVER_DIR=${SERVER_DIR}
    ports:
      - 8000:8000
