services:
  db:
    container_name: ${PROJECT_NAME}-db
    image: postgres:${POSTGRES_VERSION}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    ports:
      - "127.0.0.1:${POSTGRES_PORT}:5432"
    volumes:
      - ${POSTGRES_DATA-./config/db}:/var/lib/postgresql/data
