[project]
name = "server"
version = "0.1.0"
authors = [
    {name = "heonjin", email = "koun012@naver.com"},
]
dependencies = [
    "fastapi>=0.111.1",
    "prisma>=0.13.1",
]
requires-python = "==3.12.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
